ALTER TABLE "availability" ALTER COLUMN "availability_id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "competence_profile" ALTER COLUMN "competence_profile_id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "competence" ALTER COLUMN "competence_id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "person" ALTER COLUMN "person_id" SET GENERATED BY DEFAULT;--> statement-breakpoint
ALTER TABLE "role" ALTER COLUMN "role_id" SET GENERATED BY DEFAULT;