CREATE TABLE "application" (
	"availability_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "application_availability_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"person_id" integer,
	"status_id" integer,
	"created_at" date
);
--> statement-breakpoint
CREATE TABLE "status" (
	"status_id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "status_status_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255)
);
--> statement-breakpoint
ALTER TABLE "application" ADD CONSTRAINT "application_person_id_person_person_id_fk" FOREIGN KEY ("person_id") REFERENCES "public"."person"("person_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "application" ADD CONSTRAINT "application_status_id_status_status_id_fk" FOREIGN KEY ("status_id") REFERENCES "public"."status"("status_id") ON DELETE no action ON UPDATE no action;